controller_list:
  - name: fake_a_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: a
    pose: close